packages/fleetops-api/server/src/Notifications/OrderAssigned.php
=> view details button has been removed

api/resources/lang/en/messages.php
=> load changed as order

packages/fleetops-api/server/src/Models/Order.php
=> order config uuid added

packages/fleetops-api/server/src/Http/Controllers/Api/v1/OrderController.php
=> order view waypoints changed

packages/fleetops-api/server/src/Http/Controllers/Api/v1/OrderController.php
=> Order change destination funtionality changed

packages/fleetops-engine/addon/controllers/operations/orders/index/new.js
=> disabled multiple dropoff

api/resources/lang/en/messages.php, packages/fleetops-api/server/src/Http/Controllers/Internal/v1/OrderController.php
=> Order import start date added

packages/core-api/src/Traits/HasApiControllerBehavior.php
=> Driver availability

console/app/routes/console.js
=> default order view set

packages/fleetops-api/server/src/Http/Controllers/Api/v1/OrderController.php
=> #26081 bug fix

packages/core-api/src/Traits/HasApiControllerBehavior.php
=> timezone issue has been fixed in driver availability & orders list

console/translations/en-us.yaml, packages/fleetops-api/server/src/Http/Controllers/Api/v1/OrderController.php, packages/fleetops-engine/addon/controllers/operations/orders/index/new.js, packages/fleetops-engine/addon/templates/operations/orders/index/new.hbs
=> Fleetbase frontend

packages/fleetops-api/server/src/Http/Controllers/Internal/v1/OrderController.php
=> Unauthenticated error messge fix

packages/core-api/src/Models/User.php
=> Wrongly committed file removed

api/app/Services/LocationTranslatorService.php, api/resources/lang/en/places.php, api/resources/lang/es/places.php, packages/fleetops-api/server/src/Http/Resources/v1/Waypoint.php
=> language translation for location

api/resources/lang/en/places.php, api/resources/lang/es/places.php
=> Feature translation

packages/fleetops-api/server/src/Exports/OrderExport.php
=> Removed Customer in order export

packages/fleetops-api/server/src/Http/Resources/v1/Order.php
=> created_by and updated by name added in the api response

packages/fleetops-engine/addon/components/order/schedule-card.js
=> refresh with pagination issue fix

packages/fleetops-engine/addon/components/order/schedule-card.js, packages/fleetops-engine/addon/controllers/operations/scheduler/index.js, packages/fleetops-engine/addon/routes/operations/scheduler/index.js, packages/fleetops-engine/addon/templates/operations/scheduler/index.hbs
=> pagination with refresh issue fixed

packages/fleetops-engine/addon/components/order/schedule-card.js
=> fix for calendar

console/app/routes/console/home.js, console/translations/de-de.yml, console/translations/en-us.yaml, console/translations/es-ES.yml, console/translations/fr-fr.yml, console/translations/it-IT.yml, console/translations/vi-vn.yaml, packages/ember-ui/addon/components/filters-picker.hbs, packages/ember-ui/addon/components/filters-picker/button.hbs, packages/ember-ui/addon/components/modal/default.hbs, packages/ember-ui/addon/components/modals/export-form.hbs, packages/ember-ui/addon/components/visible-column-picker.hbs, packages/fleetops-engine/addon/controllers/operations/orders/index/new.js
=> default page redirection

console/app/styles/console.css
=> sticky pagination

packages/ember-ui/addon/components/phone-input.js
=> Fix phone no problem

packages/fleetops-engine/addon/components/calendar-filter.hbs, packages/fleetops-engine/addon/components/order/schedule-card.hbs, packages/fleetops-engine/addon/controllers/operations/scheduler/index.js
=> design fix

packages/fleetops-engine/addon/components/order/schedule-card.hbs, packages/fleetops-engine/addon/controllers/operations/scheduler/index.js, packages/fleetops-engine/addon/templates/operations/scheduler/index.hbs
=> fix for design

console/translations/de-de.yml, console/translations/en-us.yaml, console/translations/es-ES.yml, console/translations/fr-fr.yml, console/translations/it-IT.yml, console/translations/pl-pl.yml, console/translations/vi-vn.yaml, packages/ember-ui/addon/components/badge.hbs, packages/fleetops-engine/addon/components/modals/order-event.hbs, packages/fleetops-engine/addon/components/order/schedule-card.hbs, packages/fleetops-engine/addon/components/order/schedule-card.js, packages/fleetops-engine/addon/controllers/operations/scheduler/index.js
=> integrate translation

console/translations/de-de.yml, console/translations/en-us.yaml, console/translations/es-ES.yml, console/translations/fr-fr.yml, console/translations/it-IT.yml, console/translations/pl-pl.yml, console/translations/vi-vn.yaml, packages/ember-ui/addon/components/badge.hbs, packages/fleetops-engine/addon/components/issue-form-panel.hbs, packages/iam-engine/addon/components/widget/iam-metrics.hbs
=> fix for status

console/translations/vi-vn.yaml, packages/fleetops-engine/addon/components/order/schedule-card.hbs, packages/fleetops-engine/addon/controllers/operations/scheduler/index.js
=> orderid fix

packages/fleetops-engine/addon/components/modals/order-event.hbs, packages/fleetops-engine/addon/components/order/schedule-card.hbs
=> integrate disabled for complete order

packages/ember-ui/addon/components/table/cell/dropoff.js
=> fix for design break

console/app/controllers/console/account/index.js, console/app/controllers/console/admin/branding.js, console/app/controllers/console/settings/index.js, console/config/environment.js, packages/fleetops-engine/addon/components/admin/avatar-management.js, packages/fleetops-engine/addon/components/fuel-report-form-panel.js, packages/fleetops-engine/addon/components/parking-form-panel.js, packages/fleetops-engine/addon/components/toll-report-form-panel.js, packages/fleetops-engine/addon/controllers/operations/orders/index/new.js
=> Feature: S3 file import

packages/fleetops-engine/addon/components/fuel-report-form-panel.js, packages/fleetops-engine/addon/components/issue-form-panel.js, packages/fleetops-engine/addon/components/toll-report-form-panel.js
=> Review: Code review suggestions added

packages/core-api/src/Services/GoCardlessBillingRequestService.php
=> updated the logic for customer deduplication

packages/fleetops-api/server/src/Exports/OrdersImportErrorsExport.php, packages/fleetops-api/server/src/Http/Controllers/Internal/v1/OrderController.php
=> Fix: Error log file headers issue fixed

api/config/services.php, api/database/seeders/PlanPricingSeeder.php, packages/core-api/src/Http/Controllers/Internal/v1/BillingRequestController.php, packages/core-api/src/Http/Controllers/Internal/v1/OnboardController.php, packages/core-api/src/Http/Controllers/Internal/v1/PlanController.php, packages/core-api/src/Http/Controllers/Internal/v1/UserController.php, packages/core-api/src/Services/GoCardlessBillingRequestService.php, packages/core-api/src/routes.php
=> Integrate new api and convert gbp to eur

console/app/controllers/auth/login.js
=> fix for login redirect

api/resources/lang/de/messages.php, api/resources/lang/en/messages.php, api/resources/lang/es/messages.php, api/resources/lang/fr/messages.php, api/resources/lang/it/messages.php, api/resources/lang/vi/messages.php, packages/core-api/src/Http/Controllers/Internal/v1/UserController.php, packages/core-api/src/Traits/HasApiControllerBehavior.php, packages/fleetops-api/server/src/Http/Requests/Internal/CreateDriverRequest.php
=> Fix: duplicate check for the driver and vehicle table

packages/fleetops-api/server/src/Models/Order.php
=> Fix: Null check added for location

api/resources/lang/de/messages.php, api/resources/lang/en/messages.php, api/resources/lang/es/messages.php, api/resources/lang/fr/messages.php, api/resources/lang/it/messages.php, api/resources/lang/vi/messages.php, packages/fleetops-api/server/src/Http/Controllers/Internal/v1/OrderController.php
=> Fix:  import order

packages/core-api/src/Models/Setting.php
=> Fix: Default theme to Light

api/resources/lang/de/messages.php, api/resources/lang/en/messages.php, api/resources/lang/es/messages.php, api/resources/lang/fr/messages.php, api/resources/lang/it/messages.php, api/resources/lang/vi/messages.php, packages/core-api/src/Traits/HasApiControllerBehavior.php
=> Fix: Co-ordination validate

console/app/routes/billing/success.js, packages/ember-core/addon/utils/fleetbase-api-fetch.js, packages/ember-core/addon/utils/load-installed-extensions.js
=> fix for engine issue

packages/core-api/src/Traits/HasApiControllerBehavior.php
=> Fix: create place

packages/core-api/src/Http/Controllers/Internal/v1/ChargebeeWebhookController.php
=> fix for user not found

packages/fleetops-api/server/src/Models/Order.php
=> Fix: location destination

packages/ember-ui/addon/components/coordinates-input.hbs
=> revert: co-ordinates

packages/core-api/src/Http/Controllers/Internal/v1/ChargebeeWebhookController.php
=> duplicate webhook fix

api/database/migrations/2025_07_15_053134_remove_company_plan_id_foreign_key_from_payments_table.php, console/app/templates/auth/verification.hbs, console/app/templates/onboard/verify-email.hbs, packages/core-api/src/Http/Controllers/Internal/v1/ChargebeeWebhookController.php
=> Feat! chargebeeintegration

api/deploy.sh, console/app/controllers/onboard/index.js, console/config/environment.js
=> include charge bee values in environment

console/app/controllers/onboard/index.js, console/app/routes/billing/success.js, packages/core-api/src/Http/Controllers/Internal/v1/ChargebeeWebhookController.php, packages/core-api/src/Http/Controllers/Internal/v1/TestChargeController.php, packages/core-api/src/routes.php
=> validation for no of webusers and no of app users

packages/core-api/src/Traits/HasApiControllerBehavior.php, packages/ember-ui/addon/components/layout/header.js
=> Fix: duplicate check

packages/core-api/src/Traits/HasApiControllerBehavior.php, packages/ember-ui/addon/components/coordinates-input.hbs, packages/fleetops-engine/addon/components/place-form-panel.js
=> Fix: co-ordiate issue validation

api/app/Http/Controllers/Api/v1/DriverController.php, packages/fleetops-api/server/src/Models/Driver.php
=> Fix: token update fix

packages/fleetops-engine/addon/controllers/management/drivers/index.js, packages/fleetops-engine/addon/controllers/management/vehicles/index.js
=> fix: driver, vehicle page side bar issue fix

console/app/routes/console/admin.js
=> Leave request bugfix

console/config/environment.js, packages/fleetops-engine/addon/components/leaves-panel.hbs, packages/fleetops-engine/addon/components/leaves-panel.js, packages/fleetops-engine/addon/controllers/management/leaves/index.js, packages/fleetops-engine/addon/controllers/management/leaves/index/details.js, packages/fleetops-engine/addon/services/context-panel.js, packages/fleetops-engine/addon/templates/management/leaves/index/details.hbs
in view approve and reject functionality
hide edit
close functionality
=> Integrate view functionality for leave

packages/core-api/src/Http/Controllers/Internal/v1/PlanController.php, packages/core-api/src/Http/Controllers/Internal/v1/UserController.php
=> fix for console error

packages/core-api/src/Http/Controllers/Internal/v1/PlanController.php
=> include user model

packages/core-api/src/Http/Controllers/Internal/v1/UserController.php
=> Fix login new

console/app/controllers/auth/login.js
=> fix for login

console/app/controllers/auth/login.js, packages/fleetops-api/server/src/Http/Filter/IssueFilter.php, packages/fleetops-engine/addon/controllers/management/leaves/index/details.js
=> fixed issue filter and hide alert

packages/fleetops-api/server/src/Http/Filter/IssueFilter.php
=> fix for filter

api/app/Http/Controllers/Api/v1/LeaveRequestController.php
=> Feat! leave filter fix

packages/fleetops-engine/addon/controllers/management/leaves/index.js, packages/fleetops-engine/addon/routes/management/leaves/index.js
=> fix for pagination and filter

packages/fleetops-api/server/src/Http/Controllers/Internal/v1/OrderController.php
=> Fix: facility sequence

packages/core-api/src/Http/Controllers/Internal/v1/UserController.php, packages/core-api/src/Models/User.php
=> Fix: set default to en-gb

packages/core-api/src/Http/Controllers/Internal/v1/ChargebeeWebhookController.php
=> fix for handle payment 500

packages/core-api/src/Http/Controllers/Internal/v1/ChargebeeWebhookController.php
=> fix for payment sucess

packages/core-api/src/Http/Controllers/Internal/v1/ChargebeeWebhookController.php
=> payment fail fix

packages/core-api/src/Http/Controllers/Internal/v1/ChargebeeWebhookController.php
=> subscription check

console/app/controllers/auth/two-fa.js
=> transition aborted fix

packages/core-api/src/Http/Controllers/Internal/v1/OnboardController.php
=> Fix: verfication email

console/translations/de-de.yml, console/translations/en-gb.yml, console/translations/es-ES.yml, console/translations/fr-fr.yml, console/translations/it-IT.yml, console/translations/pl-pl.yml, console/translations/vi-vn.yaml, packages/ember-ui/addon/components/table/cell/dropoff.hbs, packages/fleetops-engine/addon/controllers/management/leaves/index.js, packages/fleetops-engine/addon/templates/management/leaves/index.hbs
=> fix: leave page filter fix with translation

console/app/templates/onboard/index.hbs
=> fix: save password popup in onboard form

packages/fleetops-api/server/src/routes.php
=> Fix: Removed WayPoint cache

packages/fleetops-api/server/src/Models/Place.php
=> Fix: fixed the street 1 and street 2 data correctly importing

packages/core-api/src/Http/Controllers/FleetbaseController.php, packages/core-api/src/Http/Middleware/ClearCacheAfterDelete.php, packages/fleetops-api/server/src/Http/Controllers/Internal/v1/DriverController.php, packages/fleetops-api/server/src/Http/Controllers/Internal/v1/VehicleController.php
=> Fix: Cleared cached data in list api

packages/fleetops-api/server/src/Http/Controllers/Internal/v1/OrderController.php
=> Fix: order import invalid file issue

packages/core-api/src/Traits/HasApiControllerBehavior.php, packages/fleetops-engine/addon/components/fleet-vehicle-listing.js
=> Fix: fleetVehicles

packages/ember-ui/addon/styles/components/dropdown.css
=> fix: fixed the dropoff column vertical alignment in the order page

packages/fleetops-api/server/src/Http/Controllers/Internal/v1/DriverController.php, packages/fleetops-api/server/src/Http/Controllers/Internal/v1/FleetController.php, packages/fleetops-api/server/src/Http/Controllers/Internal/v1/PlaceController.php, packages/fleetops-api/server/src/Http/Controllers/Internal/v1/VehicleController.php
=> Fix: headers validation 

console/translations/en-gb.yml, packages/ember-ui/addon/components/date-picker.hbs, packages/ember-ui/addon/components/date-picker.js, packages/ember-ui/addon/components/modals/export-form.hbs, packages/ember-ui/addon/components/modals/export-form.js, packages/ember-ui/addon/styles/components/dropdown.css, packages/ember-ui/addon/styles/layout/next.css
=> Afp 26 fix

packages/fleetops-api/server/src/Traits/ImportErrorHandler.php
=> fix: hotfix for validation error-message

packages/fleetops-api/server/src/Http/Resources/Internal/v1/Vehicle.php, packages/fleetops-api/server/src/Http/Resources/v1/FleetVehicle.php
=> Fix: updated the fleets on list

console/app/services/analytics.js, console/translations/de-de.yml, console/translations/en-gb.yml, console/translations/en-us.yaml, console/translations/es-ES.yml, console/translations/fr-fr.yml, console/translations/it-IT.yml, console/translations/pl-pl.yml, packages/ember-ui/addon/styles/components/ember-power-select.css, packages/fleetops-api/addon/components/vehicle-panel/details.hbs, packages/fleetops-data/addon/models/driver.js, packages/fleetops-data/addon/models/fleet.js, packages/fleetops-data/addon/models/vehicle.js, packages/fleetops-data/addon/serializers/driver.js, packages/fleetops-engine/addon/components/driver-form-panel.hbs, packages/fleetops-engine/addon/components/driver-form-panel.js, packages/fleetops-engine/addon/components/driver-panel/details.hbs, packages/fleetops-engine/addon/components/vehicle-form-panel.hbs, packages/fleetops-engine/addon/components/vehicle-form-panel.js, packages/fleetops-engine/addon/components/vehicle-panel/details.hbs, packages/fleetops-engine/addon/controllers/management/drivers/index.js, packages/fleetops-engine/addon/controllers/management/fleets/index.js, packages/fleetops-engine/addon/controllers/management/places/index.js, packages/fleetops-engine/addon/controllers/management/vehicles/index.js, packages/fleetops-engine/addon/controllers/operations/orders/index.js
=> Feat: implemented fleet selection in drivers and vehicles

packages/core-api/src/Services/SubscriptionUpdateService.php
=> fix: updated the code to update the subscription that are due today

packages/core-api/src/Support/ActionMapper.php, packages/fleetops-api/server/src/Http/Controllers/Internal/v1/DriverController.php
=> Fix: delete drivers

packages/fleetops-api/server/src/Http/Controllers/Internal/v1/DriverController.php, packages/fleetops-api/server/src/Http/Controllers/Internal/v1/FleetController.php
=> Fix: fleet assignment

api/app/Http/Controllers/Api/v1/ShiftAssignmentController.php, api/app/Services/ShiftAssignmentService.php
=> 27938 api to save finalised allocation data

packages/fleetops-engine/addon/controllers/operations/scheduler/index.js
=> fix: fixed the start date error in the calendar page edit

packages/fleetops-engine/addon/controllers/management/drivers/index.js, packages/fleetops-engine/addon/controllers/management/places/index.js
=> Fix: fixed the issues in the drivers and state in the list

api/app/Services/ShiftAssignmentService.php
=> Aa 4 use block id in data retrieval

console/translations/en-gb.yml, console/translations/en-us.yaml, console/translations/es-ES.yml, console/translations/fr-fr.yml, packages/fleetops-engine/addon/components/modals/import-modal.hbs, packages/fleetops-engine/addon/components/modals/order-import.hbs, packages/fleetops-engine/addon/controllers/operations/orders/index/new.js
Updated translations and modal components to support partial import success messages, displaying counts of successful and failed records. Improved error handling and feedback in the order import workflow, including more detailed results in the modal and controller logic.
=> fix: Enhance order import modal with partial success feedback

packages/core-api/src/Http/Filter/RoleFilter.php, packages/ember-ui/addon/styles/layout/next.css, packages/iam-engine/addon/components/modals/user-form.hbs
=> Fix: design issues in user creation modal and roles list restriction

packages/core-api/src/Traits/HasApiModelBehavior.php, packages/fleetops-api/server/src/Models/Order.php, packages/fleetops-engine/server/src/Models/Order.php
=> fix for trip id

packages/ember-ui/addon/components/filters-picker.js
=> fix: filter input field fix

packages/fleetops-api/server/src/Http/Controllers/Internal/v1/OrderController.php
stop2 yard arrival value is missing then check and set stop2 yar departure value
=> stop2yardarrivalis missing then take stop2yarddeprture

console/translations/en-gb.yml, packages/fleetops-engine/addon/components/order/schedule-card.js
Updated translation keys to use more specific variable names for driver and vehicle availability. Enhanced the decline handler in schedule-card.js to restore all relevant order assignment properties and increased the delay before reopening the edit modal to ensure proper state restoration.
=> Fix: Improve order assignment restoration logic

api/app/Http/Controllers/Api/v1/ShiftAssignmentController.php, api/app/Services/ShiftAssignmentService.php
=> feat: Implemented the bulk allocation modification

packages/fleetops-engine/addon/components/auto-allocation-picker.hbs, packages/fleetops-engine/addon/components/auto-allocation-picker.js
=> fix for autoallocation

packages/fleetops-engine/addon/controllers/operations/orders/index.js, packages/fleetops-engine/addon/controllers/operations/orders/index/new.js, packages/fleetops-engine/addon/routes/operations/orders/index.js
Refactored fleet column to use direct fleet name reference and removed unnecessary cell component and action. Updated order creation controller to avoid page refresh after file download and upload, preserving pagination state. Enhanced route model hook to asynchronously load fleet data for orders with fleet_uuid, improving data consistency.
=> Fix: Improve fleet data loading and pagination handling

api/app/Services/ShiftAssignmentService.php
=> Added vehicle data to shiftassignment request data

packages/fleetops-engine/addon/components/auto-allocation-picker.js
=> fix for dynamic url

api/app/Http/Controllers/Api/v1/ShiftAssignmentController.php, api/app/Services/ShiftAssignmentService.php
=> fix: fixed the no trips available issue during fleet selection

packages/ember-ui/addon/components/modal/layouts/confirm.hbs
=> refactor: text design update

packages/fleetops-engine/addon/components/auto-allocation-picker.js, packages/fleetops-engine/addon/controllers/operations/orders/index.js
=> fix: removed the timezone during data retrieval

packages/fleetops-engine/addon/controllers/management/maintenance-schedule/index/edit.js, packages/fleetops-engine/addon/controllers/management/maintenance-schedule/index/new.js
=> fix: checking loading vehicle name in the details

api/app/Http/Controllers/Api/v1/LeaveRequestController.php
=> fix for vehiclemaintanence filter
